name: Waka Readme

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          SHOW_SHORT_INFO: False
          SHOW_LOC_CHART: False
          SHOW_PROJECTS: False
          SHOW_PROFILE_VIEWS: False
